layout(local_size_x=8, local_size_y=8) in;
layout(binding=0) uniform sampler2D DepthTexture;
layout(r16f, binding=0) uniform writeonly image2D OutDepth;
layout(location=0) uniform vec4 u_depth;
layout(location=1) uniform vec4 u_screen;
#include "ao_common.glsl"
void main(){
 ivec2 px=ivec2(gl_GlobalInvocationID.xy); ivec2 size=imageSize(OutDepth); if(any(greaterThanEqual(px,size))) return;
 vec2 uv=(vec2(px)+0.5)/vec2(size);
 float d=texelFetch(DepthTexture,px,0).r;
 imageStore(OutDepth,px,vec4(d));
}
