#ifndef R_BACKEND_H
#define R_BACKEND_H

#include "q_stdinc.h"

#define R_BACKEND_MAX_PROFILE_SLOTS 128

typedef enum render_blend_factor_e
{
	R_BLEND_FACTOR_INVALID = 0,
	R_BLEND_FACTOR_ZERO,
	R_BLEND_FACTOR_ONE,
	R_BLEND_FACTOR_SRC_ALPHA,
	R_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
	R_BLEND_FACTOR_DST_ALPHA,
	R_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
	R_BLEND_FACTOR_SRC_COLOR,
	R_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
	R_BLEND_FACTOR_DST_COLOR,
	R_BLEND_FACTOR_ONE_MINUS_DST_COLOR
} render_blend_factor_t;

typedef enum render_backend_resource_type_e
{
	R_BACKEND_RESOURCE_NONE = 0,
	R_BACKEND_RESOURCE_FRAMEBUFFER,
	R_BACKEND_RESOURCE_TEXTURE,
	R_BACKEND_RESOURCE_BUFFER
} render_backend_resource_type_t;

typedef enum render_backend_resource_slot_e
{
	R_BACKEND_RESOURCE_SLOT_NONE = 0,
	R_BACKEND_RESOURCE_SLOT_SCENE_FBO,
	R_BACKEND_RESOURCE_SLOT_SCENE_COLOR,
	R_BACKEND_RESOURCE_SLOT_SCENE_VELOCITY,
	R_BACKEND_RESOURCE_SLOT_SCENE_DEPTH,
	R_BACKEND_RESOURCE_SLOT_RESOLVED_SCENE_FBO,
	R_BACKEND_RESOURCE_SLOT_RESOLVED_SCENE_COLOR,
	R_BACKEND_RESOURCE_SLOT_RESOLVED_SCENE_VELOCITY,
	R_BACKEND_RESOURCE_SLOT_COMPOSITE_FBO,
	R_BACKEND_RESOURCE_SLOT_COMPOSITE_COLOR,
	R_BACKEND_RESOURCE_SLOT_COMPOSITE_DEPTH,
	R_BACKEND_RESOURCE_SLOT_SHADOW_SUN_DEPTH,
	R_BACKEND_RESOURCE_SLOT_VELOCITY,
	R_BACKEND_RESOURCE_SLOT_COUNT
} render_backend_resource_slot_t;

typedef struct render_backend_resource_ref_s
{
	unsigned char type;
	unsigned short slot;
} render_backend_resource_ref_t;

typedef enum render_backend_primitive_e
{
	R_BACKEND_PRIMITIVE_TRIANGLES = 0,
	R_BACKEND_PRIMITIVE_TRIANGLE_FAN,
	R_BACKEND_PRIMITIVE_LINES,
	R_BACKEND_PRIMITIVE_POINTS
} render_backend_primitive_t;

#endif
