#!/usr/bin/env python3
"""Extract TODO/FIXME-style comments into a markdown triage report."""

from __future__ import annotations

import argparse
import pathlib
import re
from dataclasses import dataclass


DEFAULT_ROOTS = ("Quake", "common")
EXCLUDE_PARTS = {
    "lodepng.c",
    "lodepng.h",
    "stb_image.h",
    "stb_image_write.h",
    "miniz.c",
    "miniz.h",
}

PATTERN = re.compile(r"\b(TODO|FIXME)\b[:\s-]*(.*)", re.IGNORECASE)


@dataclass
class Finding:
    path: pathlib.Path
    line: int
    tag: str
    text: str


def should_scan(path: pathlib.Path) -> bool:
    if path.suffix.lower() not in {".c", ".h", ".cpp", ".hpp", ".glsl", ".vert", ".frag"}:
        return False
    return path.name not in EXCLUDE_PARTS


def collect(repo_root: pathlib.Path) -> list[Finding]:
    findings: list[Finding] = []

    for root in DEFAULT_ROOTS:
        base = repo_root / root
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file() or not should_scan(path):
                continue
            rel = path.relative_to(repo_root)
            try:
                lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
            except OSError:
                continue
            for idx, line in enumerate(lines, start=1):
                m = PATTERN.search(line)
                if not m:
                    continue
                tag = m.group(1).upper()
                text = (m.group(2) or "").strip()
                findings.append(Finding(rel, idx, tag, text))

    findings.sort(key=lambda f: (str(f.path), f.line))
    return findings


def render(findings: list[Finding]) -> str:
    out: list[str] = []
    out.append("# TODO/FIXME Triage Report")
    out.append("")
    out.append("Generated by `python/extract_todos.py`.")
    out.append("")
    out.append(f"Total findings: **{len(findings)}**")
    out.append("")
    out.append("| File | Line | Tag | Note |")
    out.append("| --- | ---: | --- | --- |")

    for f in findings:
        note = f.text.replace("|", "\\|") if f.text else ""
        out.append(f"| `{f.path.as_posix()}` | {f.line} | {f.tag} | {note} |")

    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parents[1],
        help="Repository root path",
    )
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=pathlib.Path("docs/TODO_TRIAGE.md"),
        help="Output markdown path (relative to repo root if not absolute)",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    out_path = args.out
    if not out_path.is_absolute():
        out_path = repo_root / out_path

    findings = collect(repo_root)
    content = render(findings)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(findings)} findings to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
