/*
Copyright (C) 1996-2001 Id Software, Inc.
Copyright (C) 2002-2009 John Fitzgibbons and others
Copyright (C) 2010-2014 QuakeSpasm developers

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#ifndef _GL_TEXMAN_H
#define _GL_TEXMAN_H

//gl_texmgr.h -- fitzquake's texture manager. manages opengl texture images

#include "texture_handles.h"

typedef struct gltexture_s {
//managed by texture manager
	/* LEGACY_GL_HANDLE / REF_GL_PRIVATE:
	 * These native GL fields are intentionally still visible during migration.
	 * Phase-3 goal is inventory + accessor candidates, not full opacity yet. */
	GLenum			target;
	GLuint			texnum;
	GLuint64		bindless_handle;
	struct gltexture_s	*next;
	qmodel_t		*owner;
//managed by image loading
	char			name[64];
	unsigned short		width; //size of image as it exists in opengl
	unsigned short		height; //size of image as it exists in opengl
	unsigned short		depth; //size of image as it exists in opengl
	unsigned char		compression; //compression rate (1 = uncompressed)
	textureflags_t		flags;
	char			source_file[MAX_QPATH]; //relative filepath to data source, or "" if source is in memory
	src_offset_t		source_offset; //byte offset into file, or memory address
	enum srcformat		source_format; //format of pixel data (indexed, lightmap, or rgba)
	unsigned int		source_width; //size of image in source data
	unsigned int		source_height; //size of image in source data
	unsigned short		source_crc; //generated by source data before modifications
	signed char			shirt; //0-13 shirt color, or -1 if never colormapped
	signed char			pants; //0-13 pants color, or -1 if never colormapped
//used for rendering
	int			visframe; //matches r_framecount if texture was bound this frame
	int			mipmap; //number of mip levels uploaded (0 = unknown)
	GLenum		internal_format; //GL internal format used for upload
} gltexture_t;

/* PHASE3_BOUNDARY_CANDIDATE:
 * Candidate accessor split for future opaque migration:
 * - keep CPU/metadata fields externally readable,
 * - route texnum/target/bindless/internal_format via gl_texmgr accessors. */
/* TODO_RESOURCE_BOUNDARY / TODO_GL_DECONTAMINATION:
 * Suggested first accessors for opaque migration:
 * - TexMgr_GetNativeHandle(const gltexture_t*)
 * - TexMgr_GetTarget(const gltexture_t*)
 * - TexMgr_GetBindlessHandle(const gltexture_t*)
 * - TexMgr_GetInternalFormat(const gltexture_t*) */

extern gltexture_t *notexture;
extern gltexture_t *nulltexture;
extern gltexture_t *whitetexture;
extern gltexture_t *greytexture;
extern gltexture_t *blacktexture;
extern gltexture_t *lavaemissivetexture;

extern GLuint gl_palette_lut;
extern GLuint gl_palette_buffer[2];

extern unsigned int d_8to24table[256];
extern unsigned int d_8to24table_fbright[256];
extern unsigned int d_8to24table_nobright[256];
extern unsigned int d_8to24table_conchars[256];

typedef enum
{
	TEXMGR_PALMODE_STANDARD = 0,
	TEXMGR_PALMODE_ALPHABRIGHT,
	TEXMGR_PALMODE_NOBRIGHT
} texmgr_palmode_t;

void TexMgr_DecodeIndexedToRGBA (const byte *indexed, int pixel_count, int transparent_index, texmgr_palmode_t mode, byte *rgba);
void TexMgr_BuildFullbrightRGBA (const byte *indexed, int pixel_count, int transparent_index, byte *rgba);

extern GLint gl_max_texture_size;

// TEXTURE MANAGER

float TexMgr_FrameUsage (void);
gltexture_t *TexMgr_FindTexture (qmodel_t *owner, const char *name);
gltexture_t *TexMgr_NewTexture (void);
void TexMgr_FreeTexture (gltexture_t *kill);
void TexMgr_FreeTextures (unsigned int flags, unsigned int mask);
void TexMgr_FreeTexturesForOwner (qmodel_t *owner);
void TexMgr_NewGame (void);
void TexMgr_Init (void);
void TexMgr_DeleteTextureObjects (void);
void TexMgr_ApplySettings (void);
qboolean TexMgr_UsesFilterOverride (void);

// IMAGE LOADING
gltexture_t *TexMgr_LoadImage (qmodel_t *owner, const char *name, int width, int height, enum srcformat format,
                               byte *data, const char *source_file, src_offset_t source_offset, unsigned flags);
gltexture_t *TexMgr_LoadImageEx (qmodel_t *owner, const char *name, int width, int height, int depth, enum srcformat format,
                               byte *data, const char *source_file, src_offset_t source_offset, unsigned flags);
GLuint TexMgr_LoadDDS (const char *path);
void TexMgr_ReloadImage (gltexture_t *glt, int shirt, int pants);
void TexMgr_ReloadImages (void);
void TexMgr_ReloadNobrightImages (void);
void TexMgr_SRGBTextures_f (cvar_t *var);
qboolean TexMgr_ShouldUseSRGB (const char *name, enum srcformat format, unsigned flags, const char *source_file);
qboolean TexMgr_IsReady (void);
void TexMgr_Trace (const char *fmt, ...);
/* TODO_RESOURCE_BOUNDARY / REF_GL_PRIVATE:
 * Accessor-first path for future gltexture_t opacity. */
GLuint TexMgr_GetNativeHandle (const gltexture_t *glt);
GLenum TexMgr_GetTarget (const gltexture_t *glt);
GLuint64 TexMgr_GetBindlessHandle (const gltexture_t *glt);
GLenum TexMgr_GetInternalFormat (const gltexture_t *glt);

int TexMgr_Pad(int s);
int TexMgr_SafeTextureSize (int s);
int TexMgr_PadConditional (int s);

// TEXTURE BINDING & TEXTURE UNIT SWITCHING

qboolean GL_Bind (GLenum texunit, gltexture_t *texture);
qboolean GL_BindNative (GLenum texunit, GLenum type, GLuint handle);
void GL_BindTextures (GLuint first, GLsizei count, gltexture_t **textures);
void GL_DeleteNativeTexture (GLuint texnum);
void GL_ClearBindings (void);

#endif	/* _GL_TEXMAN_H */
